# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-10 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hiba',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('kapcsolattarto_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
