# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-10 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibak', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiba',
            name='status',
            field=models.CharField(blank=True, choices=[('e', 'Elkuldve'), ('f', 'Fogadva'), ('h', 'Elharitva'), ('v', 'Visszaigazolva')], default='e', help_text='Hiba Allapot', max_length=1),
        ),
    ]
