# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-10 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibak', '0003_hiba_leiras'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiba',
            name='cim',
            field=models.CharField(default='SOME STRING', help_text='Adja meg a hiba cimet', max_length=200),
        ),
        migrations.AddField(
            model_name='hiba',
            name='nev',
            field=models.CharField(default='SOME STRING', help_text='Adja meg a hiba bejelento nevet', max_length=200),
        ),
        migrations.AlterField(
            model_name='hiba',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
