# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-10 23:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hibak', '0004_auto_20170711_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hiba',
            old_name='status',
            new_name='statusz',
        ),
    ]
