# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-11 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hibak', '0005_auto_20170711_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alkalmazott',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nev', models.CharField(default='', help_text='Alkalmazott neve', max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='hiba',
            name='cim',
            field=models.CharField(default='', help_text='Adja meg a hiba cimet', max_length=200),
        ),
        migrations.AlterField(
            model_name='hiba',
            name='nev',
            field=models.CharField(default='', help_text='Adja meg a hiba bejelento nevet', max_length=200),
        ),
        migrations.AddField(
            model_name='hiba',
            name='elharito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hibak.Alkalmazott'),
        ),
    ]
