# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-11 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hibak', '0007_auto_20170711_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErtesitettAlkalmazott',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='alkalmazott',
            name='cim',
            field=models.CharField(default='1074 Budapest Teszt Elek utca 22', help_text='Alkalmazott cime', max_length=200),
        ),
        migrations.AlterField(
            model_name='alkalmazott',
            name='email',
            field=models.EmailField(default='tesztelek@gmail.com', help_text='Alkalmazott email cime', max_length=254),
        ),
        migrations.AlterField(
            model_name='alkalmazott',
            name='nev',
            field=models.CharField(default='Teszt Elek', help_text='Alkalmazott neve', max_length=200),
        ),
        migrations.AddField(
            model_name='ertesitettalkalmazott',
            name='alkalmazott',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hibak.Alkalmazott'),
        ),
    ]
