# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-11 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hibak', '0008_auto_20170711_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visszajelzes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uzenet', models.TextField()),
                ('hiba', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hibak.Hiba')),
            ],
        ),
    ]
